name: Lint Semgrep

on:
  workflow_dispatch:
  push:

# As we don't have an unlimited amount of GitHub action minutes, let's
# cancel any currently running job or workflow in the same concurrency group
# if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Semgrep
        run: |
          semgrep \
            --config "p/terraform" \
            --error \
            --strict \
            --metrics=off \
            --verbose
